### ISSUE TITLE
Radix dialog --removed-body-scroll-bar-size variable set to 0

### ISSUE THREAD

**Issue by arekrgw** [emilkowalski/vaul#285] opened 2024-02-29 09:10 UTC
When opening normal radix dialog, css variable `--removed-body-scroll-bar-size` on body element is set to some pixel value that represents the scrollbar width when it hides. That's not the case with this lib Drawer, variable is set to 0px all the time, creating content shift on the page

To reproduce you need to have to have some content on the page and then open the right/left drawer.

After some investigation it looks like the css `position` override to `fixed` from `relative` on body element is the issue.

![image](https://github.com/emilkowalski/vaul/assets/34128433/0512776b-dc89-4986-98a9-635c6e9bbfe8)

**Comment by dschlabach** [comment] 2024-03-09 17:23
As a temporary workaround for those of us using a right-aligned drawer, you can do this:

```
body[data-scroll-locked] {
  padding-right: 15px !important;
}
```

**Comment by emilkowalski** [comment] 2024-03-16 21:56
Cam you provide a demo with reproduction?

**Comment by dschlabach** [comment] 2024-03-19 11:08
Hey! I've created a reproduction highlighting the issue here:

https://stackblitz.com/edit/nextjs-nqthme

**Comment by hamishtaplin** [comment] 2024-03-29 11:49
Also experiencing this having to come to this from using shadcn

**Comment by voyageur-design** [comment] 2024-04-28 18:21
Also Experiencing this when using right or left aligned drawers

**Comment by Andrii-Antoniuk** [comment] 2024-06-03 20:09
This is still an issue in 0.9.1.
The issue is that both `html` and `body` tags receive padding-right and margin-right, respectively.
I don't see any references to such styles in the repo, so is this coming from Radix/some dep? 🤷 
The workaround would be to set `!important` on either `html` or `body` with styles.

New reproduction link (with 0.9.1) - https://stackblitz.com/edit/nextjs-j6eglw?file=app%2FDrawer.tsx
@emilkowalski FYI

**Comment by HarleySalas** [comment] 2024-06-28 20:52
> don't see any references to such styles in the repo, so is this coming from Radix/some dep? 🤷 

It must be something in vaul, as when you use the radix library alone, there are no such issues with the scrollbar.

**Comment by Andrii-Antoniuk** [comment] 2024-07-01 07:35
> It must be something in vaul, as when you use the radix library alone, there are no such issues with the scrollbar.
> 
> 

Simple CTRL+F didn't find anything 🤔 Could it be that it was a bug in radix before, but now in latest version they have fixed it?

**Comment by erip2** [comment] 2024-07-18 08:29
I investigated this problem further because as others have mentioned here, this problem doesn't occur on the radix dialog component.

I tried to see how the [react-remove-scroll-bar](https://github.com/theKashey/react-remove-scroll-bar) library was running behind the scenes. It is this library that sets the `--removed-body-scroll-bar-size`. To be more specific, it's the [getGapWidth](https://github.com/theKashey/react-remove-scroll-bar/blob/master/src/utils.ts#L29) function inside utils.js.

The components difference is on `document.documentElement.clientWidth` value. On the Radix Dialog component, this value is correct, but on the Drawer one is the same as `window.innerWidth` which causes the value of the gap to be always 0.

The reason for these values to be the same is that vaul [adds classes to the body](https://github.com/emilkowalski/vaul/blob/40d3a69825df25e04ffe1e52c99c3461d785f31a/src/use-position-fixed.ts#L37) which affect the `clientWidth` value.

Then I figured to add the `noBodyProps` prop, but the flickering problem remained. I found out another difference between the component, and that it was a class in `<html>`, a `padding-right` that was added when using the vaul component.

This padding was also [added by vaul](https://github.com/emilkowalski/vaul/blob/40d3a69825df25e04ffe1e52c99c3461d785f31a/src/use-prevent-scroll.ts#L121). Easy to remove though, by another prop: `disablePreventScroll`.

So, by adding both of these props, you can remove the flicker effect when opening the drawer on the right (or left).

--

Anyway, I am not sure of the other effects of these props, as they may break other functionalities in some cases, but at the moment, this is a fine solution for me.

**Comment by emilkowalski** [comment] 2024-09-14 18:46
This has been fixed now, the `--removed-body-scroll-bar-size` CSS variable should now set the correct value automatically.

**Closed by emilkowalski** 2024-09-14 18:46 UTC
