### ISSUE TITLE
Drawer Disappears with 'dismissible' Set to False and Snap Points Defined

### ISSUE THREAD

**Issue by IsaiahHarris** [emilkowalski/vaul#173] opened 2023-11-19 00:32 UTC
### Summary
The drawer component disappears when dragged to the bottom despite having 'dismissible' set to false and multiple snap points defined.

### Steps to Reproduce
1. Configure a Drawer component with 'dismissible' set to false.
2. Define multiple snap points for the drawer.
3. Attempt to drag the drawer to the bottom

### Expected Behavior
The drawer should stay visible and snap to the defined points, and it should not be possible to dismiss it by dragging to the bottom.

### Actual Behavior
The drawer disappears or closes when dragged to the bottom, contrary to the expected behavior given the 'dismissible' set to false.

**Comment by imclint21** [comment] 2023-11-21 16:00
Same issue here #161

**Comment by emilkowalski** [comment] 2023-11-21 18:44
Duplicate of #161

**Closed by emilkowalski** 2023-11-21 18:44 UTC
