### ISSUE TITLE
Bug in animation(in/out) with `vaul-drawer-wrapper`

### ISSUE THREAD

**Issue by bernardinorafael** [emilkowalski/vaul#144] opened 2023-10-15 04:19 UTC
I couldn't figure out what is causing this bug in the animation, it's certainly the attribute that needs to be passed to shouldScaleBackground.

I tried several ways to encompass my components with a container with the attribute, but they all cause this effect in the animation.

```
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="pt-BR">
        <body
          className={cn(
            'bg-zinc-950 text-zinc-400 antialiased',
            'font-sans scrollbar-thin scrollbar-thumb-zinc-900',
            fontSans.variable,
            fontHeading.variable,
          )}
        >
          <div vaul-drawer-wrapper="">
            <Header />

            <main>
              <Providers>{children}</Providers>
            </main>

            <Footer />
          </div>
        </body>
      </html>
    </>
  )
}
```

![ezgif-5-67900d2be1](https://github.com/emilkowalski/vaul/assets/102430354/b6c3affc-cdc3-4d54-872b-65851ca9cc40)

**Comment by emilkowalski** [comment] 2023-10-15 12:18
Please provide a codesandbox demo with a reproduction.

**Comment by 0xBN** [comment] 2023-10-19 21:27
I had this same thing happen to me, where it looks like there is flashing content upon closing. The cause was setting a height for my app container.  Sample below below


`
export default function App({ Component, pageProps }) {
  return (
              <Container className="app-container" type="div">
                <RootLayout>
                  <Component {...pageProps} />
                </RootLayout>
              </Container>
  )
}
`

and my stylesheet had this height on it, once the height was removed the drawer component worked as expected.
`
.app-container {
  height: 100vh; // remove this
}
`

**Comment by bernardinorafael** [comment] 2023-10-20 02:32
> I had this same thing happen to me, where it looks like there is flashing content upon closing. The cause was setting a height for my app container. Sample below below
> 
> ```
> export default function App({ Component, pageProps }) {
>   return (
>             <Container className="app-container" type="div">
>               <RootLayout>
>                 <Component {...pageProps} />
>               </RootLayout>
>             </Container>
>   )
> }
> ```
> 
> and my stylesheet had this height on it, once the height was removed the drawer component worked as expected.
> 
> ```
> .app-container {
>   height: 100vh; // remove this
> }
> ```

in my case, the problem only runs on based chromium browsers... I tested on safari and works fine...

**Comment by emilkowalski** [comment] 2023-10-20 11:13
Again, please provide a codesandbox demo so I can test it as I'm unable to reproduce it myself.

**Comment by bernardinorafael** [comment] 2023-10-20 22:18
@emilkowalski 

I apologize for my delay in responding, I put my repo in a codesandbox demo and I was unable to reproduce the error, the Vaul component worked perfectly... I will investigate the possible cause further over the weekend and test the solution proposed by @0xBN...

As previously stated, this error only occurs in Chromium-based browsers, in Firefox and Safari there was no such error.

If there is any news I will inform you here.

**Closed** 2023-11-06 19:04 UTC
