### ISSUE TITLE
Page jumps to top when opening the drawer 

### ISSUE THREAD

**Issue by OrenMag** [emilkowalski/vaul#318] opened 2024-04-04 12:27 UTC
Loom: 

https://www.loom.com/share/c146667a27774baebbcebeeb6985313f

Seems like the top of body is set to 0 upon opening (as well as right, left and position fixed)

vaul version: 0.9.0

Couldn't create reproducible sandbox

**Comment by LouisGS44** [comment] 2024-04-06 13:20
Same here, version 0.9.0

**Comment by maiconcarraro** [comment] 2024-04-06 14:01
I believe the problem can be related to this line:

https://github.com/emilkowalski/vaul/blob/a30da7d1618afd8b33637982695f0676130346ff/src/use-prevent-scroll.ts#L260

I'm only facing this issue for Iphone devices, not Androids

**Comment by Orestli** [comment] 2024-04-12 08:56
Any updates?

**Comment by michael-convertdigital** [comment] 2024-05-06 11:55
i'm experiencing the same issue in remix, it seems to happen randomly, maybe every 3rd or 4th close of the drawer

**Comment by emilkowalski** [comment] 2024-05-07 10:29
> Couldn't create reproducible sandbox

This proves that this is a tough issue to fix. I'd love to fix it, but without a consistent reproduction I could only guess as to what is causing the problem. Removing `window.scrollTo(0, 0)` might help potentially, but it'll break other stuff.

**Comment by levitatejay** [comment] 2024-05-12 05:16
> It only happens when testing through iOS devices, it **won't work** emulating Chrome DevTools w/ iOS user-agent.

Your repro is reliable for me, I toggle Chrome dev tools and the iPhone view setting and I'm unable to open the drawer

<img width="728" alt="image" src="https://github.com/emilkowalski/vaul/assets/13340760/23cc4bed-d0fc-44a4-beb5-9f24b7aab9ec">

Do you know a workaround? I've had to disable the drawer because it won't work with window virtual scrolling on mobile

**Comment by levitatejay** [comment] 2024-05-22 07:43
I have managed to fix the issue in my project by updating to `v.0.9.1` and adding `noBodyStyles` and `preventScrollRestoration={false}` to my Drawer

**Comment by levitatejay** [comment] 2024-05-22 07:53
I fixed this in my project by upgrading to v0.9.1 and adding `noBodyStyles` and `preventScrollRestoration={false}`

**Comment by levitatejay** [comment] 2024-06-04 08:31
> I fixed this in my project by upgrading to v0.9.1 and adding `noBodyStyles` and `preventScrollRestoration={false}`

Turns out it was only fixed in the Chrome mobile dev tools and the issue still occurs in iOS Safari. 

I'm using the drawer with the TanStack virtual scroller using the window as the scroller. With `noBodyStyles` and `preventScrollRestoration={false}` it jumps to the top of the page when the drawer is open, and while there is a touch interaction with the drawer it temporarily resets to the correct page position

**Comment by michael-convertdigital** [comment] 2024-06-05 03:51
after upgrading to v0.9.1 in remix i now get hydration errors

`Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
     at Root (/Users/convert/Documents/projects/cue/packages/ui/node_modules/vaul/dist/index.mjs:749:23)
     at Drawer2 (/Users/convert/Documents/projects/cue/packages/ui/@/components/ui/drawer.tsx:6:19)
     at /Users/convert/Documents/projects/cue/packages/ui/src/components/Slideout/Slideout.tsx:15:5
`

**Comment by KyGuy2002** [comment] 2024-07-08 22:27
I am seeing this as well.  None of the suggested workarounds fixed it.

Interestingly, it does not happen when the website is installed as a PWA on IOS, and only when in the browser.

I am using the Chrome IOS App.

**Comment by maiconcarraro** [comment] 2024-07-09 01:02
> I am seeing this as well. None of the suggested workarounds fixed it.
> 
> I am using the Chrome IOS App.

They pushed a fix for standalone apps that can be related to your findings: https://github.com/emilkowalski/vaul/pull/277

**Comment by sarevok89** [comment] 2024-07-18 07:53
Using the `disablePreventScroll={true}` fixed the issue in the iOS PWA for me. It says it's `true` by default but I had to add it myself:

![image](https://github.com/user-attachments/assets/3ee05011-173a-4489-ba65-d91b5e26ff40)

**Comment by PankajDesaiCakewalk** [comment] 2024-09-05 11:20
> after upgrading to v0.9.1 in remix i now get hydration errors
> 
> ```
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's
> output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this,
> useLayoutEffect should only be used in components that render exclusively on the client. See
> https://reactjs.org/link/uselayouteffect-ssr for common fixes.
>      at Root (/Users/convert/Documents/projects/cue/packages/ui/node_modules/vaul/dist/index.mjs:749:23)
>      at Drawer2 (/Users/convert/Documents/projects/cue/packages/ui/@/components/ui/drawer.tsx:6:19)
>      at /Users/convert/Documents/projects/cue/packages/ui/src/components/Slideout/Slideout.tsx:15:5
> ```

have you get any solution

**Comment by emilkowalski** [comment] 2024-09-07 10:56
Scrolling issue should be fixed in #406.

`useLayoutEffect` hydration errors are fixed in #367

**Closed by emilkowalski** 2024-09-07 10:56 UTC
