### ISSUE TITLE
Drawer still dimissible with snappoints

### ISSUE THREAD

**Issue by imclint21** [emilkowalski/vaul#161] opened 2023-11-07 21:56 UTC
Hi,

I open this issue for centralise this problem:

After updating to the last version (0.7.8), and using snappoints, the drawer still dismissible, when it shouldn't.

Here is the code I'm using:

```tsx
<Drawer.Root
	shouldScaleBackground={true}
	open={open}
	snapPoints={[snapPoint1 || "290px", snapPoint2 || "650px"]}
	activeSnapPoint={snap}
	setActiveSnapPoint={setSnap}
	dismissible={false}
	modal={false}>
</Drawer.Root>
```

Regards

**Comment by emilkowalski** [comment] 2023-11-10 01:06
This has been fixed in #166

**Comment by imclint21** [comment] 2023-11-11 21:28
Just updated to the last version, and it does not seems fixed anyway =(

**Comment by emilkowalski** [comment] 2023-11-11 23:59
Please provide a codesandbox demo in that case, I'm unable to reproduce.

**Comment by imclint21** [comment] 2023-11-12 19:26
Alright @emilkowalski I'll try to do ASAP, in the meanwhile, is it possible to create a kind of fallback? like trigger reopening when its close?

**Comment by imclint21** [comment] 2023-11-13 20:49
Okey I did it @emilkowalski, first, here is the repo: [vaul-dismissible-snappoints-issue](https://github.com/hypeproxy/vaul-dismissible-snappoints-issue)

🔗  https://codesandbox.io/p/github/hypeproxy/vaul-dismissible-snappoints-issue/master

**Comment by imclint21** [comment] 2023-11-14 07:27
It might be a misunderstood of the vision that you have of the a non-dismissible drawer actually.

For me `snapPoints` and `dismissible={false}` should give a drawer that can only reach snap points, and cannot be closed at all without dragging the drawer to the bottom of the screen.

**Comment by imclint21** [comment] 2023-11-14 07:37
I just tried this, it works as a fallback, but I'd prefer a real non-dismissible drawer.

Don't work however with too small timeout, like 100ms.

```tsx
useEffect(() => {
	if (!open) setTimeout(() => {
		setOpen(true);
		setSnap(snapPoint1 || "290px");
	}, 500);
}, [open]);
```

**Comment by emilkowalski** [comment] 2023-11-21 18:44
What's the problem with [this one](https://codesandbox.io/p/github/hypeproxy/vaul-dismissible-snappoints-issue/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp8ol7fx00083b6hkkxfjq4o%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp8ol7fw00033b6hhnhrp2pg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp8ol7fx00053b6h4v6zl4zg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8ol7fx00073b6hgqmcxt1w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp8ol7fw00033b6hhnhrp2pg%2522%253A%257B%2522id%2522%253A%2522clp8ol7fw00033b6hhnhrp2pg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clp8ol7fx00073b6hgqmcxt1w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8ol7fx00063b6hod04qcdm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp8ol7fx00073b6hgqmcxt1w%2522%252C%2522activeTabId%2522%253A%2522clp8ol7fx00063b6hod04qcdm%2522%257D%252C%2522clp8ol7fx00053b6h4v6zl4zg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8ol7fx00043b6hap43pv5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clp8ol7fx00053b6h4v6zl4zg%2522%252C%2522activeTabId%2522%253A%2522clp8ol7fx00043b6hap43pv5a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)? Your code was incorrect, I edited a bunch of lines and it works?

**Comment by emilkowalski** [comment] 2023-11-21 19:24
@IsaiahHarris Here you go mate - [example](https://codesandbox.io/p/devbox/drawer-snap-points-forked-8rs2zk?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnb09z4a00093b6faal0dvqs%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnb09z4a00043b6fahmmv1go%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnb09z4a00063b6fzir493ee%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnb09z4a00083b6fp71udpgx%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8q28ye00733b6ifrctbifg%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp8q29jl00a53b6if26l2x8h%2522%257D%255D%252C%2522sizes%2522%253A%255B33.333333333333336%252C33.333333333333336%252C33.333333333333336%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnb09z4a00043b6fahmmv1go%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnb09z4a00033b6fys2ugfub%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fmy-drawer.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A17%257D%255D%257D%255D%252C%2522id%2522%253A%2522clnb09z4a00043b6fahmmv1go%2522%252C%2522activeTabId%2522%253A%2522clnb09z4a00033b6fys2ugfub%2522%257D%252C%2522clnb09z4a00083b6fp71udpgx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnb09z4a00073b6fa7dd34c3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clnb09z4a00083b6fp71udpgx%2522%252C%2522activeTabId%2522%253A%2522clnb09z4a00073b6fa7dd34c3%2522%257D%252C%2522clnb09z4a00063b6fzir493ee%2522%253A%257B%2522id%2522%253A%2522clnb09z4a00063b6fzir493ee%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnb09z4a00053b6fjv6ujb1m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clnb09z4a00053b6fjv6ujb1m%2522%257D%252C%2522clp8q28ye00733b6ifrctbifg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8q26xn00703b6is44gcgry%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp8q28ye00733b6ifrctbifg%2522%252C%2522activeTabId%2522%253A%2522clp8q26xn00703b6is44gcgry%2522%257D%252C%2522clp8q29jl00a53b6if26l2x8h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp8q29dr00a03b6iaot4zb96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp8q29jl00a53b6if26l2x8h%2522%252C%2522activeTabId%2522%253A%2522clp8q29dr00a03b6iaot4zb96%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by imclint21** [comment] 2023-11-21 22:41
No sorry I'm sure @emilkowalski will find time to manage this issue, then I could release our customers dashboard :D

**Comment by emilkowalski** [comment] 2023-11-21 23:06
> @emilkowalski is there a communication issue I am missing?
> 
> The issue is the drawer with snapPoints, and dismissible={false}, will still close.
> 
> The expected behavior is that the drawer should not close.
> 
> Currently there is no known way to have a drawer that stays on the page and is non dismissible that has snapPoints.
> 
> Please let me know if you need any more information about the issue if I can clear up any confusion.
> 
> cc: @imclint21 @xih

No communication issues, I just can’t reproduce it, it doesn’t close for me 🤔 This is interesting, I’ll look into it as soon as I have some spare time. It’ll be most likely this weekend as I’m pretty busy. Sorry about that!

**Comment by imclint21** [comment] 2023-11-22 16:44
> > @emilkowalski is there a communication issue I am missing?
> > The issue is the drawer with snapPoints, and dismissible={false}, will still close.
> > The expected behavior is that the drawer should not close.
> > Currently there is no known way to have a drawer that stays on the page and is non dismissible that has snapPoints.
> > Please let me know if you need any more information about the issue if I can clear up any confusion.
> > cc: @imclint21 @xih
> 
> No communication issues, I just can’t reproduce it, it doesn’t close for me 🤔 This is interesting, I’ll look into it as soon as I have some spare time. It’ll be most likely this weekend as I’m pretty busy. Sorry about that!

Which browser do you use btw?

**Comment by imclint21** [comment] 2023-11-22 18:09
me too, but I was asking to @emilkowalski :)

**Comment by rortan134** [comment] 2023-12-01 22:14
Same problem here

**Comment by rortan134** [comment] 2023-12-02 01:48
Dirty workaround while this isn't fixed

Use forceMount on the content and override the `translate3d` style used to move the drawer out of the screen with the exposed `--snap-point-height` variable


```tsx
"use client";

import * as React from "react";
import { Drawer } from "vaul";

const snapPoints = ["148px", "355px", 1];
// Taken from https://github.com/emilkowalski/vaul/blob/main/src/constants.ts
const VELOCITY_THRESHOLD = 0.4;

export function MyDrawer() {
  const [activeSnapPoint, setActiveSnapPoint] = React.useState<
    number | string | null
  >("148px");
  const drawerSheetRef = React.useRef<HTMLDivElement>(null);
  const previousDragYRef = React.useRef(0);
  const dragStartTimeRef = React.useRef<Date>();
  const minSnapPointHeight = drawerSheetRef.current
    ? getComputedStyle(drawerSheetRef.current).getPropertyValue(
        "--snap-point-height",
      )
    : "0px";

  function preventDrawerClose() {
    setActiveSnapPoint(snapPoints[0]);
    drawerSheetRef.current?.style.setProperty(
      "transform",
      `translate3d(0, ${minSnapPointHeight}, 0)`,
    );
  }

  function checkDrawerBoundaries() {
    if (
      drawerSheetRef.current &&
      drawerSheetRef.current.getBoundingClientRect().top >
        parseInt(minSnapPointHeight)
    ) {
      preventDrawerClose();
    }
  }

  // Stops flicks from closing the drawer
  function handleOnPointerUp(event: React.PointerEvent) {
    const dragEndTime = new Date().getTime();
    const dragStartTime = dragStartTimeRef.current
      ? dragStartTimeRef.current.getTime()
      : 0;
    const timeTaken = dragEndTime - dragStartTime;
    const distanceMoved = previousDragYRef.current - event.screenY;
    const dragVelocity = Math.abs(distanceMoved) / timeTaken;
    const hasVelocityMetThreshold = dragVelocity > VELOCITY_THRESHOLD;
    const hasDraggedUp = distanceMoved > 0;

    if (hasVelocityMetThreshold && !hasDraggedUp) {
      // setTimeout makes sure updates are ran after vaul's
      setTimeout(() => {
        preventDrawerClose();
        checkDrawerBoundaries();
      }, 10);
    }
  }

  return (
    <Drawer.Root
      open
      dismissible={false}
      modal={false}
      snapPoints={snapPoints}
      activeSnapPoint={activeSnapPoint}
      setActiveSnapPoint={setActiveSnapPoint}
      onDrag={checkDrawerBoundaries}
    >
      <Drawer.Portal forceMount>
        <Drawer.Content
          ref={drawerSheetRef}
          asChild // asChild is needed in order to merge onPointer events without overriding vaul's
        >
          <div
            data-state="open" // always open
            vaul-drawer-visible="true"
            className="flex flex-col max-w-md mx-auto w-full p-4 pt-5"
            onPointerDown={(event) => {
              previousDragYRef.current = event.screenY;
              dragStartTimeRef.current = new Date();
            }}
            onPointerUp={handleOnPointerUp}
          >
            {/* ... */}
          </div>
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
}
```


[Full example here](https://codesandbox.io/p/devbox/drawer-snap-points-forked-4gyrw9?file=%2Fapp%2Fmy-drawer.tsx)

**Closed** 2023-12-04 13:32 UTC

**Comment by emilkowalski** [comment] 2023-12-17 01:58
@IsaiahHarris This is released now!
