### ISSUE TITLE
Incredibly laggy performance on androids.

### ISSUE THREAD

**Issue by shrihari-prakash** [emilkowalski/vaul#306] opened 2024-03-22 14:22 UTC
First of all, very nice component. The interactions are very natural. However, when I tried the component on a mid range android phone, I was quite shocked by the frame rate that the drawer opens. See here a sample:

https://github.com/emilkowalski/vaul/assets/35889246/6076e2ea-df4d-4605-b158-43eb2f767d65

You can see all the other animations in the app are lightning fast and smooth except for the drawer. Matter of fact, the recording looks smoother than how I experienced it in person. I am not sure if everyone using the component is testing it only on top of the line phones. Even on pixels, there is frame drops. Am I missing an option or something that could make the situation better? The app is totally unusable on androids because of this. I know building such components are not easy, yet I just want to bring this to notice.

**Comment by emilkowalski** [comment] 2024-04-06 16:13
Please provide a demo with reproduction.

**Comment by cervantes-x** [comment] 2024-05-03 09:52
I am experiencing the same issue and only on Android devices. Any update on this?

**Comment by cervantes-x** [comment] 2024-05-03 11:53
I'm not sure if this is considered a correct solution but at least as a workaround it helped a lot to add `willChange: "transform"` to the element that has the `vaul-drawer-wrapper` data attribute. In my case:

```jsx
      <body
        style={{ willChange: "transform" }}
        vaul-drawer-wrapper=""
        className={cn(fontClasses)}
      >
        ...
      </body>
```

I also added it to the  ` <Drawer.Overlay />`:

```jsx
  <Drawer.Overlay
    style={{
      willChange: "transform",
    }}
  />
```

**Comment by shrihari-prakash** [comment] 2024-05-04 06:23
Hello @cervantes-x , 
Thanks a lot for sharing your findings. Unfortunately for me though, even setting the `willChange` property does not help :(. But what I am noticing though is it's slow only on Mediatek devices specifically. Qualcomm devices have only a slight frame drop. This happens even with basic usage of the drawer. So it might be hard to reproduce without an actual device.

**Comment by emilkowalski** [comment] 2024-09-16 16:52
Closing for now as I'm simply unable to reproduce as I'd probably need your specific device.

If you are experiencing performance issues I'd advice you to use the drawer without the `shouldScaleBackground` prop.

**Closed by emilkowalski** 2024-09-16 16:52 UTC
