### ISSUE TITLE
seeing strange scroll behavior when tray is open / closes

### ISSUE THREAD

**Issue by sgrund14** [emilkowalski/vaul#79] opened 2023-08-30 15:41 UTC
experiencing a weird background scroll when the tray is open

https://github.com/emilkowalski/vaul/assets/14083701/b33e7b75-bbc6-4b43-b83d-fa8c1b57d6f1

context: recently refactored the element scrolling to be the document root, rather than a scrollable div a few children down. problem only started occurring after this change

seeing it happen on iOS safari, mobile chrome, embedded instagram browser... wondering if it is a vaul thing or a radix thing or a browser thing

**Comment by emilkowalski** [comment] 2023-08-30 15:56
Can you provide a reproduction in codesandbox? I can’t reproduce it myself.

**Comment by desaihetav** [comment] 2023-08-31 05:56
I'm experiencing a similar issue. I believe something's going wrong when the trigger is positioned fixed. And this is happening only on mobile devices, works fine on desktop browser in responsive mode.

In my case, when the page content isn't scrolled at all, everything works fine.
But on opening drawer when the page content is scrolled, it auto scrolls page content to top and touch actions in the drawer start behaving weirdly. When I tap on 'open second drawer' or anywhere in the drawer content for that matter, it just scrolls the page content back to where it was before opening drawers and again scrolls to top when I lift my finger.

Reproduction in codesandbox: https://codesandbox.io/p/sandbox/drawer-nested-forked-4cmvz2

https://github.com/emilkowalski/vaul/assets/36413698/9d03e8fb-4833-49e2-9d1c-735da751e15a

**Comment by sgrund14** [comment] 2023-08-31 19:41
ya I was having this issue too @desaihetav, thanks for dropping the codepen 🙏  in my video it's doing that same scroll to the top then back to the element thing

**Comment by emilkowalski** [comment] 2023-08-31 23:21
@desaihetav This bug was caused by the nested drawer running the same hook as the root drawer. Fixed in #82.

@sgrund14 I think your issue is different. I'd need a codesandbox repro to fix it.

**Comment by desaihetav** [comment] 2023-09-01 04:31
Awesome, thanks @emilkowalski! When're you planning to push a new version which includes this fix?

**Comment by emilkowalski** [comment] 2023-09-01 08:16
I'll publish one over the weekend.

**Comment by emilkowalski** [comment] 2023-09-09 10:37
Closing for now, feel free to open a new issue once you have a reproduction 👍🏻

**Closed by emilkowalski** 2023-09-09 10:37 UTC

**Comment by sgrund14** [comment] 2023-09-09 17:17
hey @emilkowalski, actually ended up finding the issue 🙏  I was using a Drawer within a Drawer, but the inner drawer was not using vaul's `NestedDrawer` component.

There was also something I had in my setup that that was breaking the solution you merged in https://github.com/emilkowalski/vaul/pull/82

```html {
   scroll-behavior: smooth;
}```

if this is present on your global.css file, the scroll thing comes back. I just removed it from mine to fix, but weird edge case

repro:
https://codesandbox.io/p/sandbox/drawer-reproduce-scroll-issue-forked-dtnlx9?file=%2Fpages%2F_app.tsx%3A16%2C1
