### ISSUE TITLE
`onOpenChange` still getting called twice when user clicks outside of Drawer

### ISSUE THREAD

**Issue by phxgg** [emilkowalski/vaul#345] opened 2024-05-07 18:10 UTC
Related issue that was closed: #290 

My guess is that this issue was reintroduced by accident.

Read this comment for more info https://github.com/emilkowalski/vaul/pull/291#issuecomment-2002213281

**Comment by misaelvillaverde** [comment] 2024-08-05 19:06
I think the issue is that the vaul is triggering the close action twice.

After setting a ref to prevent changing my state by the onOpenChange function being called with the same value twice, the vaul was still being closed with my controller state staying `true` :(

**Comment by almousa1990** [comment] 2024-09-08 07:03
+1

**Comment by emilkowalski** [comment] 2024-09-13 18:08
Fixed in #408

**Closed by emilkowalski** 2024-09-13 18:08 UTC
