### ISSUE TITLE
Drawer is broken for Iphone devices when opening a new one while closing another [v0.9.4 and v0.9.3]

### ISSUE THREAD

**Issue by maiconcarraro** [emilkowalski/vaul#433] opened 2024-09-18 20:00 UTC
Codesandbox: https://codesandbox.io/p/devbox/drawer-non-dismissable-forked-qtt8jp?workspaceId=0f47f685-6d3f-426b-b796-e3a871dffa37&embed=1&file=%2Fpackage.json

This issue only happens when using the Iphone device itself, when using Chrome dev tools to emulate it doesn't trigger the same behavior. In v0.9.2 this is not an issue, only for v0.9.3 and v0.9.4.

Recording of the issue:
- If your page is at the top the issue doesn't happen, only after you scroll and try to interact
- Once you open the first drawer, if you try to open a second one + close the first one, the touch doesn't work.

https://github.com/user-attachments/assets/5e01420d-5e1f-4387-94bb-3d3e8dfdc2e6

Iphone information:
![image](https://github.com/user-attachments/assets/3a6478df-a8ad-4063-af1b-f2fefe7c9a51)

**Comment by renekahr** [comment] 2024-09-18 20:38
Same for me. I also can't open nested drawers.

**Comment by KirdesMF** [comment] 2024-09-19 12:04
Updating to 0.9.4 and we have nearly the same issue in our app.
If there is only one drawer on a page, there is no issue but once there 2 or more drawer the issue is happening. It becomes Impossible to open any drawer.
Happens in iOS and Android.

**Comment by maiconcarraro** [comment] 2024-09-19 13:25
@KirdesMF we don't have this issue for android, do you face this on web as well? Unfortunately Iphone is hard to debug for my environment, if I could reproduce w/ android I'd more information to help emil

**Comment by KirdesMF** [comment] 2024-09-19 13:52
@maiconcarraro No issue at all on web.
About Android one of our dev tried on a android mobile and get the same issue.
We tried to debug with Xcode but nothing really helpful.

**Comment by maiconcarraro** [comment] 2024-09-19 13:54
@KirdesMF if your dev can debug the android using chrome inspect https://developer.chrome.com/docs/devtools/remote-debugging

**Comment by emilkowalski** [comment] 2024-09-22 22:54
Fixed in #436. Will release a new version after I do some more manual testing and improvements.

**Closed by emilkowalski** 2024-09-22 22:54 UTC
