### ISSUE TITLE
Drawer is not pushed above keyboard if the drawer content becomes scrollable through keyboard open

### ISSUE THREAD

**Issue by maltesa** [emilkowalski/vaul#39] opened 2023-08-11 08:14 UTC
https://github.com/emilkowalski/vaul/assets/4067078/d68f49f7-3e1b-422f-9786-6204c3d2bb39

If: 
- the content of the drawer is potentially scrollable but has no overflowing content while the keyboard is invisible
- and contains a text-input ...

... in that case, I was expecting the drawer to increase it's height by the keyboard height.

Example: https://codesandbox.io/p/sandbox/drawer-scrollable-forked-wr6r9p?file=%2Fapp%2Fmy-drawer.tsx%3A30%2C15

I tried to fix it by setting the drawer max-height as height when the keyboard is open. That kind of works:
https://codesandbox.io/p/sandbox/drawer-scrollable-forked-4878pm?file=%2Fapp%2Fmy-drawer.tsx%3A6%2C29

Also: I've recognized that #21 arises randomly (have seen it on ios and android). My guess is that it happens when an input at the bottom of the drawer content is focused. In that case, browsers seems to add extra margin to the drawer bottom, in order to push the input above the keyboard. 
Btw: Issue #21 constantly arises on ios when focusing the bottom input in the "fixed" example.

**Comment by emilkowalski** [comment] 2023-08-11 09:27
I'll look into this.

As to #21, I'm not able to reproduce it, but I will look into it as well. + The browser is not adding extra margin, I'm doing it myself, the browser would mess up the view in a whole different way otherwise.

**Comment by maltesa** [comment] 2023-08-12 10:36
> I'll look into this.
> 
> As to #21, I'm not able to reproduce it, but I will look into it as well. + The browser is not adding extra margin, I'm doing it myself, the browser would mess up the view in a whole different way otherwise.

Awesome, thank you. While checking the drawer on different devices with different browsers, I realized how very difficult it is to build a good draggable bottom sheet / drawer. Felt like browser wars again. Thank you for your work ❤️

**Comment by DennieMello** [comment] 2023-08-30 23:03
I noticed that on ios safari, the height of the modal window does not always change when the input is focused, even when it is hidden due to the appearance of the keyboard. It is difficult to reproduce the problem, as it happens randomly, in 1/20 cases.

**Comment by DennieMello** [comment] 2023-08-31 11:43
> I noticed that on ios safari, the height of the modal window does not always change when the input is focused, even when it is hidden due to the appearance of the keyboard. It is difficult to reproduce the problem, as it happens randomly, in 1/20 cases.

Example
https://github.com/emilkowalski/vaul/assets/39631512/99d74b31-8721-4ccb-90cc-1787e2083109

**Comment by emilkowalski** [comment] 2023-09-02 08:29
Thanks for reporting, both should be fixed in #83

**Closed by emilkowalski** 2023-09-02 08:29 UTC
