### ISSUE TITLE
Update from v0.9.1 to v0.9.3 CSS bug

### ISSUE THREAD

**Issue by vartdalen** [emilkowalski/vaul#422] opened 2024-09-16 13:16 UTC
"bug" 1:
Causes "background: black" to be applied to body by JavaScript (not with className) on Drawer open.

Applying black to background must be reverted or at least should be opt in.

bug 2:
Causes "pointer events: none" to be applied to <body> by JavaScript (not with className) on Drawer open.

If I open the Drawer and quickly close it by clicking on the background right away, pointer events: none is not removed from body, rendering the app uninteractive until page refresh or manual disabling of the CSS modifier.

I have reverted to v0.9.1 until further notice.

This is a great library, much love from a big fan

**Comment by emilkowalski** [comment] 2024-09-16 13:34
I'm unable to reproduce both of the bugs. Can you record a video and post it here so I can see exactly what you are doing in order to repro it?

**Comment by vartdalen** [comment] 2024-09-16 14:23
![image](https://github.com/user-attachments/assets/d977b496-d0a3-4cfa-b2b4-2d864bf1c58d)

**Comment by vartdalen** [comment] 2024-09-16 14:42
Here I am running v0.9.3.

Notice that the background: black css modifier is overriding my background image shown in previous images - only dimmed, that is not good.

![image](https://github.com/user-attachments/assets/e8b46671-1065-4468-a730-c710221ce0c3)

**Comment by vartdalen** [comment] 2024-09-16 14:44
Here I have reproduced bug 2,

I have opened and closed the drawer very quickly. It does not happen every time and is sometimes hard to reproduce.

As you can see, pointer-events: none remains on body, even though my drawer is closed, rendering the app uninteractive until page reload

![image](https://github.com/user-attachments/assets/9e38e60a-84cb-4598-a14f-0a21478189a8)

**Comment by vartdalen** [comment] 2024-09-16 14:46
I hope you revert the changes please!

**Comment by hedbladucf** [comment] 2024-09-16 15:05
I have the exact same issue. It drove me crazy for a few minutes thinking I had some other issue as my page seemed unresponsive! This a quite a nasty little bug, please fix asap. I reverted back and I no longer see the issue.

**Comment by emilkowalski** [comment] 2024-09-16 15:43
Can you provide a demo with reproduction? The exact props you are using etc. 

The black background won't be added unless you have `shouldScaleBackground` to create an iOS-like effect. 

This codesandbox runs on 0.9.3, it's the default setup. https://codesandbox.io/p/devbox/drawer-with-scale-forked-nx2glp

Are you able to reproduce it there?

**Comment by maiconcarraro** [comment] 2024-09-16 17:39
@emilkowalski 

[Code sandbox using v0.9.0](https://codesandbox.io/p/devbox/drawer-with-scale-forked-l4hvnm?workspaceId=0f47f685-6d3f-426b-b796-e3a871dffa37)

[Code sandbox using v0.9.3](https://codesandbox.io/p/devbox/drawer-with-scale-forked-ph5wc5?file=%2Fapp%2Fmy-drawer.tsx%3A12%2C65&workspaceId=0f47f685-6d3f-426b-b796-e3a871dffa37)

The condition to this to happen is:
- Remove `vaul-drawer-wrapper` or `data-vaul-drawer-wrapper` from your document
- Set `shouldScaleBackground` to **true**

You can spot the black background between contents on the >>> example
![image](https://github.com/user-attachments/assets/fcebe6ce-fb35-46d2-830a-2b1f46f88e32)


I know it's confusing, it was a "hidden" bug for people using shadcn for example that already had this prop true and maybe no reference to the wrapper, and now using the new version it makes the bug visible.
![image](https://github.com/user-attachments/assets/74f4418e-6bfa-4227-82a2-b9122676eb2c)

**Comment by emilkowalski** [comment] 2024-09-16 18:02
@maiconcarraro Thank you so much for this reproductions and explanations.

I changed `vaul-drawer-wrapper` to `data-vaul-drawer-wrapper` in version `0.9.3`, so people that updated are probably still using the old attribute. I made it backwards compatible in this PR #412, will make sure to release a new version later today and close this issue when it's released.

Once again thanks @maiconcarraro for this great explanation.

**Comment by maiconcarraro** [comment] 2024-09-16 18:07
@emilkowalski for this specific bug your change related to `vaul-drawer-wrapper` -> `data-vaul-drawer-wrapper` makes no difference.

The problem is the difference for this logic (from your PR: https://github.com/emilkowalski/vaul/pull/409/files)

![image](https://github.com/user-attachments/assets/9e5ebb8a-f6e9-4cc3-8d47-809d0ed80ccc)

Having no wrapper would return early and apply no styling, whereas the new version applies style even if wrapper is null.

![image](https://github.com/user-attachments/assets/8b34416d-97ab-4b2c-a600-ea47afdaeeee)

**Comment by emilkowalski** [comment] 2024-09-16 18:11
I agree that this is a configuration issue. Consequences of this misconfiguration where avoided before, because we returned early if there was no wrapper even if `shouldScaleBackground` was true. [This](https://github.com/emilkowalski/vaul/pull/426) PR brings back the early return. @maiconcarraro Does this PR make sense to you? Want to double-check before I merge.

**Comment by maiconcarraro** [comment] 2024-09-16 18:13
@emilkowalski same page ✅

**Comment by vartdalen** [comment] 2024-09-17 07:18
Could the issue of failing to remove the modifier be attributed to the use of React.useEffect()?

**Comment by vartdalen** [comment] 2024-09-17 07:19
> @emilkowalski for this specific bug your change related to `vaul-drawer-wrapper` -> `data-vaul-drawer-wrapper` makes no difference.
> 
> The problem is the difference for this logic (from your PR: https://github.com/emilkowalski/vaul/pull/409/files)
> 
> ![image](https://private-user-images.githubusercontent.com/13419087/367872505-9e5ebb8a-f6e9-4cc3-8d47-809d0ed80ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTc3MDUsIm5iZiI6MTcyNjU1NzQwNSwicGF0aCI6Ii8xMzQxOTA4Ny8zNjc4NzI1MDUtOWU1ZWJiOGEtZjZlOS00Y2MzLThkNDctODA5ZDBlZDgwY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzUyZmE5MjBlMDY0ZThjMTYyOTk2ZTQ0NjU5MjA0MjRkNDc0YzY2ZWJiMGNiZGY4NmVmM2NmZGI2MjA5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fFKE4cZWei8HJEK0XptvdInqCEgQM42wl_mruCwoWg)
> 
> Having no wrapper would return early and apply no styling, whereas the new version applies style even if wrapper is null.
> 
> ![image](https://private-user-images.githubusercontent.com/13419087/367872826-8b34416d-97ab-4b2c-a600-ea47afdaeeee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTc3MDUsIm5iZiI6MTcyNjU1NzQwNSwicGF0aCI6Ii8xMzQxOTA4Ny8zNjc4NzI4MjYtOGIzNDQxNmQtOTdhYi00YjJjLWE2MDAtZWE0N2FmZGFlZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGM0NGFlMDQzOTUyNTUxY2ViYjQyNmVlMzRkMDcwMGJmMjQyMDFlM2IzYWEwMWVlOGVkOWM3MmFkNTlkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1zp8RUquYqa-sP6prN8wZJpkvFeZQV2jGYmJeFHpJm4)


Could the issue of failing to remove the modifier be attributed to the use of React.useEffect()?

**Comment by emilkowalski** [comment] 2024-09-17 10:50
> of failing to remove the modifier on drawer

What `useEffect`? I'd say change the data attribute and see if the problem persists.

**Comment by vartdalen** [comment] 2024-09-18 07:29
> @vartdalen this library has no directly relation to the "pointer-events: none" logic, this is set by **radix dialog** and this bug might happen if you are using different versions of radix, you just try to follow up there, example of a very similar issue there: [[Dialog] body pointer-events: none remains after closing #1241](https://github.com/radix-ui/primitives/issues/1241)

The depicted reproduction of bug 2 does not involve bumping radix dialog, only vaul from v0.9.1 to v0.9.3

**Comment by vartdalen** [comment] 2024-09-18 11:53
I underline that in v0.9.1, opening and closing the drawer is not only avoiding the pointer event bug. It is also snappier and more reactive to quickly opening and closing the drawer in succession.

**Comment by emilkowalski** [comment] 2024-09-18 12:34
@vartdalen Again, please provide a demo with reproduction. I don't know what your exact setup is and this is critical for me to debug it.

**Comment by maiconcarraro** [comment] 2024-09-18 13:24
the only thing that could be related to this is this specific bump to radix dialog version: https://github.com/emilkowalski/vaul/pull/408/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L66

![image](https://github.com/user-attachments/assets/b8035d51-66c3-48c8-b6ab-e1407d952430)

so depending on what you have in your project you may have conflicts if you are not enforcing the same version, in my project I also have (using this since vaul 0.9.0 to solve a problem w/ cmdk and other libs)
![image](https://github.com/user-attachments/assets/bcfd42c2-40d8-461f-b952-9616e76ef0b0)

@vartdalen can you reproduce using the sandbox I sent few messages above?

**Comment by sshmaxime** [comment] 2024-09-18 13:27
@vartdalen to remove the weird black background, add `setBackgroundColorOnScale` to the root element. 

cc @emilkowalski https://github.com/emilkowalski/vaul/issues/431

**Comment by navid-az** [comment] 2024-09-18 14:09
can confirm. adding `setBackgroundColorOnScale` to the root element will in fact fix unexpected black background when Drawer is open

**Comment by emilkowalski** [comment] 2024-09-18 14:30
I've updated Vaul's version to 0.9.4 where you can keep `vaul-drawer-wrapper` instead of changing it to `data-vaul-drawer-wrapper`. This was what caused the issue on 0.9.3. Waiting on a repro demo for pointer events before closing this pone.

**Comment by hedbladucf** [comment] 2024-09-18 14:37
Thanks for updating, Emil. Cheers!

**Closed** 2024-09-22 23:53 UTC

**Comment by vartdalen** [comment] 2024-09-26 08:13
https://github.com/user-attachments/assets/26b52423-80cf-4f14-b6ee-4ca03391777c

**Comment by emilkowalski** [comment] 2024-10-02 11:55
> 2024-09-26_10-05-13-2.mp4 
> @emilkowalski

This is on purpose. It is now using CSS animations instead of CSS transitions and pointer events none are set on the body until the drawer fully closes, that's how Radix's Dialog work.
